#!/usr/bin/env python3
"""Generate synthetic fixtures for surge's test suite.

The GGUF/safetensors/tokenizer generators below are stdlib-only (struct).
The op fixture generators need numpy (--ops) and mlx + mlx_lm (--hybrid);
run those with the dsv4-venv interpreter, which has both:

    /Users/macmini/models/dsv4-venv/bin/python tools/make_fixtures.py --ops
    /Users/macmini/models/dsv4-venv/bin/python tools/make_fixtures.py --hybrid

Run once at authoring time; the produced binaries are committed to
tests/fixtures/ and are not regenerated by the build.
"""
import json
import pathlib
import struct
import sys

GGUF_MAGIC = b"GGUF"
GGUF_VERSION = 3
ALIGNMENT = 32

# sg_gguf_kv_type values, must match the enum in surge.h. Prefixed KV_ to
# keep them distinct from the sg_tensor_type values below, which use the same
# names for different numbers (KV_F32 is 6, TT_F32 is 0).
KV_I32 = 5
KV_F32 = 6
KV_BOOL = 7
KV_U32 = 4
KV_STR = 8
KV_ARR = 9

# sg_tensor_type values, must match the enum in surge.h.
TT_F32 = 0
TT_Q8_0 = 8


def _str(s: str) -> bytes:
    b = s.encode("utf-8")
    return struct.pack("<Q", len(b)) + b


def _kv_str(key: str, value: str) -> bytes:
    return _str(key) + struct.pack("<I", KV_STR) + _str(value)


def _kv_u32(key: str, value: int) -> bytes:
    return _str(key) + struct.pack("<I", KV_U32) + struct.pack("<I", value)


def _kv_i32(key: str, value: int) -> bytes:
    return _str(key) + struct.pack("<I", KV_I32) + struct.pack("<i", value)


def _kv_bool(key: str, value: bool) -> bytes:
    return _str(key) + struct.pack("<I", KV_BOOL) + struct.pack("<B", 1 if value else 0)


def _kv_arr_u32(key: str, values: list) -> bytes:
    out = _str(key) + struct.pack("<I", KV_ARR) + struct.pack("<I", KV_U32)
    out += struct.pack("<Q", len(values))
    for v in values:
        out += struct.pack("<I", v)
    return out


def _kv_f32(key: str, value: float) -> bytes:
    return _str(key) + struct.pack("<I", KV_F32) + struct.pack("<f", value)


def _kv_arr_str(key: str, values: list) -> bytes:
    out = _str(key) + struct.pack("<I", KV_ARR) + struct.pack("<I", KV_STR)
    out += struct.pack("<Q", len(values))
    for v in values:
        out += _str(v)
    return out


def _tensor_info(name: str, ttype: int, dims: list, offset: int) -> bytes:
    out = _str(name)
    out += struct.pack("<I", len(dims))
    for d in dims:
        out += struct.pack("<Q", d)
    out += struct.pack("<I", ttype)
    out += struct.pack("<Q", offset)
    return out


def write_mini_gguf(path: str) -> None:
    """Write the small GGUF v3 fixture used by tests/test_gguf.c.

    Metadata: general.architecture="qwen3_5" (str),
    qwen3_5.block_count=2 (u32), test.arr=[1,2,3] (u32 array),
    test.i32=-42 (i32), test.bool=true (bool).
    Tensors: t.f32 f32[4] = [1.0, 2.0, 3.0, 4.0];
    t.q8 Q8_0[32], one block: f16 scale 0.5 + int8 0..31.
    """
    kvs = [
        _kv_str("general.architecture", "qwen3_5"),
        _kv_u32("qwen3_5.block_count", 2),
        _kv_arr_u32("test.arr", [1, 2, 3]),
        _kv_i32("test.i32", -42),
        _kv_bool("test.bool", True),
    ]

    f32_nbytes = 4 * 4  # t.f32: f32[4]
    q8_nbytes = 34  # t.q8: Q8_0[32] = 1 block (2-byte f16 scale + 32 int8)

    off_f32 = 0
    off_q8 = ((off_f32 + f32_nbytes + ALIGNMENT - 1) // ALIGNMENT) * ALIGNMENT

    tensors = [
        _tensor_info("t.f32", TT_F32, [4], off_f32),
        _tensor_info("t.q8", TT_Q8_0, [32], off_q8),
    ]

    header = GGUF_MAGIC + struct.pack("<I", GGUF_VERSION)
    header += struct.pack("<Q", len(tensors))
    header += struct.pack("<Q", len(kvs))

    body = header + b"".join(kvs) + b"".join(tensors)
    pad = (-len(body)) % ALIGNMENT
    body += b"\x00" * pad
    assert len(body) % ALIGNMENT == 0

    data = bytearray()
    data += struct.pack("<4f", 1.0, 2.0, 3.0, 4.0)  # t.f32
    data += b"\x00" * (off_q8 - len(data))  # pad up to t.q8's offset
    data += struct.pack("<H", 0x3800)  # f16(0.5) scale
    data += struct.pack("<32b", *range(32))  # int8 0..31
    assert len(data) == off_q8 + q8_nbytes

    out = pathlib.Path(path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_bytes(body + bytes(data))


# 24 cases for tests/test_tok.c, covering: empty string, ascii prose, digits,
# contractions, code with braces/tabs, leading/trailing/internal/mixed
# whitespace, bare newlines, blank lines, CRLF, accented Latin, CJK, Hangul,
# emoji, mixed emoji+CJK+ascii, punctuation runs, and a long no-space token
# (URL). None contain literal special-token strings (e.g. "<|...|>"), since
# sg_tok_encode is plain byte-level BPE with no added-token recognition.
TOK_FIXTURE_CASES = [
    "",
    "Hello, world!",
    "The quick brown fox jumps over 13 lazy dogs, 42 times.",
    "I can't believe it's not butter. We'll see; they've done it already.",
    "0123456789",
    "Total: 5 items, cost $9.99 (approx).",
    "def foo(x):\n\treturn {'a': 1, 'b': [1, 2, 3]}\n",
    "if (x > 0) {\n    return x;\n} else {\n    return -x;\n}",
    "   leading spaces",
    "trailing spaces   ",
    "a    b     c",
    "\n\n\n",
    "line1\nline2\n\nline3",
    "a\tb\tc",
    "line1\r\nline2\r\n",
    "café naïve résumé Zürich",
    "日本語のテスト。これはテストです。",
    "안녕하세요 세계",
    "emoji test 😀🚀🎉",
    "Hello 世界 🌍!",
    "Wait... what?! No way!!! (really?)",
    "https://example.com/path?query=1&other=2",
    "line1\nline2\ttabbed",
    "   \t  mixed   whitespace\t\t  runs  ",
]


def write_tok_fixture(tokenizer_dir: str, out_path: str) -> None:
    """Generate tests/fixtures/tok_cases.jsonl from the real HF tokenizer.

    Each line is {"text": ..., "ids": [...]}, ids from
    AutoTokenizer.encode(text, add_special_tokens=False) (no BOS/EOS; Qwen's
    add_bos_token is false and there is no TemplateProcessing post_processor
    on this tokenizer, so this matches plain encode/decode with no implicit
    special tokens). Written with ensure_ascii=False so non-ASCII text is
    stored as raw UTF-8 bytes, not \\uXXXX escapes (surrogate pairs for
    astral-plane emoji would otherwise need extra decoding on the C side).

    Requires the dsv4-venv interpreter (has transformers installed):
        /Users/macmini/models/dsv4-venv/bin/python tools/make_fixtures.py --tok
    """
    from transformers import AutoTokenizer

    tok = AutoTokenizer.from_pretrained(tokenizer_dir)

    assert len(TOK_FIXTURE_CASES) == 24, \
        f"expected 24 fixture cases, got {len(TOK_FIXTURE_CASES)}"

    out = pathlib.Path(out_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("w", encoding="utf-8") as f:
        for text in TOK_FIXTURE_CASES:
            ids = tok.encode(text, add_special_tokens=False)
            decoded = tok.decode(ids)
            assert decoded == text, f"roundtrip mismatch for {text!r}: {decoded!r}"
            line = json.dumps({"text": text, "ids": ids}, ensure_ascii=False)
            f.write(line + "\n")

    print(f"wrote {out_path} ({len(TOK_FIXTURE_CASES)} cases)")


def _f32_to_bf16_bytes(x: float) -> bytes:
    """Round-to-nearest-even float32 -> bf16, packed as a little-endian u16.

    All six fixture values below (0.5, 1, 2, 3, 4, 5) are exactly
    representable in bf16 (zero mantissa bits below the truncation point),
    so this is a plain truncation for them; the round-to-nearest-even bias
    is included anyway so the helper is correct for arbitrary floats.
    """
    bits = struct.unpack("<I", struct.pack("<f", x))[0]
    rounding_bias = 0x7FFF + ((bits >> 16) & 1)
    bits = (bits + rounding_bias) >> 16
    return struct.pack("<H", bits & 0xFFFF)


def write_mini_safetensors(out_dir: str) -> None:
    """Write the small safetensors fixture used by tests/test_st.c.

    Single-shard model dir (no model.safetensors.index.json) containing
    model.safetensors and config.json {"hidden_size": 3}. Three tensors:

      w      BF16 [2, 3]  row-major 0.5, 1, 2, 3, 4, 5
      wf     F32  [4]     -1.5, 0.25, 3.0, -7.5     (added in Task 7)
      wi8    I8   [4]     an indexable-looking dtype surge does NOT index

    "wf" exists because the real Qwen3.5 checkpoint stores
    linear_attn.A_log and linear_attn.norm.weight as F32 amid otherwise-BF16
    layer weights, so st.c indexes F32 as well as BF16; without it the whole
    sg_st_tensor_f32 path would only ever run under the SURGE_ST-gated
    real-model test and would be dead code in a default `make check`.
    "wi8" pins that a third dtype is still validated-but-not-indexed.
    Both are placed after "w" at 4-byte-aligned offsets.
    """
    values = [0.5, 1.0, 2.0, 3.0, 4.0, 5.0]
    data = bytearray(b"".join(_f32_to_bf16_bytes(v) for v in values))
    assert len(data) == 12
    bf16_end = len(data)
    f32_values = [-1.5, 0.25, 3.0, -7.5]
    data += struct.pack("<4f", *f32_values)
    f32_end = len(data)
    data += struct.pack("<4b", -128, -1, 0, 127)
    i8_end = len(data)
    data = bytes(data)

    header_obj = {
        "w": {"dtype": "BF16", "shape": [2, 3], "data_offsets": [0, bf16_end]},
        "wf": {"dtype": "F32", "shape": [4], "data_offsets": [bf16_end, f32_end]},
        "wi8": {"dtype": "I8", "shape": [4], "data_offsets": [f32_end, i8_end]},
    }
    header_json = json.dumps(header_obj).encode("utf-8")
    # Pad the header with spaces (valid insignificant JSON whitespace) so the
    # data section starts 8-byte aligned, per the safetensors convention.
    total_prefix = 8 + len(header_json)
    pad = (-total_prefix) % 8
    header_json += b" " * pad

    out = pathlib.Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)

    with (out / "model.safetensors").open("wb") as f:
        f.write(struct.pack("<Q", len(header_json)))
        f.write(header_json)
        f.write(data)

    (out / "config.json").write_text(json.dumps({"hidden_size": 3}), encoding="utf-8")
    print(f"wrote {out_dir}/model.safetensors ({len(header_obj)} tensors) "
          f"and {out_dir}/config.json")


def _lcg_floats(n, seed):
    """Deterministic small floats, stdlib only (keeps --st numpy-free)."""
    out = []
    x = seed & 0xFFFFFFFF
    for _ in range(n):
        x = (1103515245 * x + 12345) & 0x7FFFFFFF
        out.append((x / 0x7FFFFFFF) * 2.0 - 1.0)
    return out


def _st_pack(tensors):
    """tensors: list of (name, dtype, shape, [float values]) -> (header, data).

    Emits F32 and BF16 only, in the given order, each at a 4-byte-aligned
    offset so both dtypes are naturally aligned (st.c skips a misaligned F32
    rather than indexing it, which would look like a missing tensor).
    """
    data = bytearray()
    header = {}
    for name, dtype, shape, values in tensors:
        pad = (-len(data)) % 4
        data += b"\x00" * pad
        begin = len(data)
        if dtype == "F32":
            data += struct.pack("<%df" % len(values), *values)
        elif dtype == "BF16":
            data += b"".join(_f32_to_bf16_bytes(v) for v in values)
        else:
            raise ValueError(dtype)
        header[name] = {"dtype": dtype, "shape": list(shape),
                        "data_offsets": [begin, len(data)]}
    return header, bytes(data)


# Tiny hybrid model dims for the mini_model_st fixture. Chosen so the two
# DeltaNet head counts differ (2 key heads feeding 4 value heads) and so
# nothing is square.
MINI_MODEL = dict(hidden=8, n_heads=2, n_kv_heads=1, head_dim=4, ffn=16, vocab=10,
                  nk=2, nv=4, dk=4, dv=4, conv_k=4)


def _mini_model_tensors(drop=None):
    """Tensor list for a 2-layer hybrid model: layer 0 linear-attn, layer 1
    full-attention. `drop` names a tensor suffix to omit (for the negative
    test that a partial group is rejected)."""
    m = MINI_MODEL
    key_dim = m["nk"] * m["dk"]
    value_dim = m["nv"] * m["dv"]
    conv_dim = 2 * key_dim + value_dim
    P = "model.language_model."
    t = []
    seed = [1]

    def add(name, dtype, shape):
        n = 1
        for d in shape:
            n *= d
        seed[0] += 1
        t.append((name, dtype, shape, _lcg_floats(n, seed[0] * 7919)))

    add(P + "embed_tokens.weight", "BF16", [m["vocab"], m["hidden"]])
    add(P + "norm.weight", "BF16", [m["hidden"]])

    for layer in (0, 1):
        L = P + "layers.%d." % layer
        add(L + "input_layernorm.weight", "BF16", [m["hidden"]])
        add(L + "post_attention_layernorm.weight", "BF16", [m["hidden"]])
        add(L + "mlp.gate_proj.weight", "BF16", [m["ffn"], m["hidden"]])
        add(L + "mlp.up_proj.weight", "BF16", [m["ffn"], m["hidden"]])
        add(L + "mlp.down_proj.weight", "BF16", [m["hidden"], m["ffn"]])
        if layer == 0:
            # A_log is BF16 and norm.weight is F32 here ON PURPOSE: the real
            # checkpoints disagree about these two (F32 in the Qwen3.5-2B,
            # BF16 in the mlx 8-bit repack of the 27B), so making one of each
            # exercises both branches of model_qwen.c's st_dense_tensor_any
            # probe in a plain `make check`.
            add(L + "linear_attn.in_proj_qkv.weight", "BF16", [conv_dim, m["hidden"]])
            add(L + "linear_attn.in_proj_z.weight", "BF16", [value_dim, m["hidden"]])
            add(L + "linear_attn.in_proj_b.weight", "BF16", [m["nv"], m["hidden"]])
            add(L + "linear_attn.in_proj_a.weight", "BF16", [m["nv"], m["hidden"]])
            add(L + "linear_attn.A_log", "BF16", [m["nv"]])
            add(L + "linear_attn.dt_bias", "BF16", [m["nv"]])
            add(L + "linear_attn.conv1d.weight", "BF16", [conv_dim, 1, m["conv_k"]])
            add(L + "linear_attn.norm.weight", "F32", [m["dv"]])
            add(L + "linear_attn.out_proj.weight", "BF16", [m["hidden"], value_dim])
        else:
            add(L + "self_attn.q_proj.weight", "BF16",
                [2 * m["n_heads"] * m["head_dim"], m["hidden"]])
            add(L + "self_attn.k_proj.weight", "BF16",
                [m["n_kv_heads"] * m["head_dim"], m["hidden"]])
            add(L + "self_attn.v_proj.weight", "BF16",
                [m["n_kv_heads"] * m["head_dim"], m["hidden"]])
            add(L + "self_attn.o_proj.weight", "BF16",
                [m["hidden"], m["n_heads"] * m["head_dim"]])
            add(L + "self_attn.q_norm.weight", "BF16", [m["head_dim"]])
            add(L + "self_attn.k_norm.weight", "BF16", [m["head_dim"]])

    if drop is not None:
        before = len(t)
        t = [x for x in t if not x[0].endswith(drop)]
        assert len(t) == before - 1, f"drop target {drop!r} matched {before - len(t)} tensors"
    return t


def write_mini_model_st(out_dir: str, drop=None) -> None:
    """Write a tiny but STRUCTURALLY REAL hybrid qwen3_5 safetensors model.

    tests/fixtures/mini_model_st/ exists so that sg_model_from_st's
    DeltaNet mapping runs in a plain `make check`. Before it, the entire
    linear-attention path in model_qwen.c was only reachable under the
    SURGE_ST-gated real-model test, i.e. it was dead code for anyone without
    a multi-GB checkpoint on disk.

    Two layers: layer 0 linear-attention (all nine ssm tensors), layer 1
    full-attention (all six attention tensors). Both carry the shared MLP and
    norms. Names use the multimodal "model.language_model." nesting the real
    checkpoint uses, so the loader's nested-name fallback is exercised too.

    tests/fixtures/mini_model_st_partial/ is the same model with
    linear_attn.dt_bias removed, so the all-nine-or-none group invariant that
    both loaders now enforce has a negative test.
    """
    m = MINI_MODEL
    header, data = _st_pack(_mini_model_tensors(drop))
    header_json = json.dumps(header).encode("utf-8")
    header_json += b" " * ((-(8 + len(header_json))) % 8)

    out = pathlib.Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    with (out / "model.safetensors").open("wb") as f:
        f.write(struct.pack("<Q", len(header_json)))
        f.write(header_json)
        f.write(data)

    cfg = {
        "model_type": "qwen3_5",
        "tie_word_embeddings": True,
        "text_config": {
            "num_hidden_layers": 2,
            "num_attention_heads": m["n_heads"],
            "num_key_value_heads": m["n_kv_heads"],
            "head_dim": m["head_dim"],
            "hidden_size": m["hidden"],
            "intermediate_size": m["ffn"],
            "vocab_size": m["vocab"],
            "rms_norm_eps": 1e-06,
            "full_attention_interval": 2,
            "linear_num_key_heads": m["nk"],
            "linear_num_value_heads": m["nv"],
            "linear_key_head_dim": m["dk"],
            "linear_value_head_dim": m["dv"],
            "linear_conv_kernel_dim": m["conv_k"],
            "rope_parameters": {"rope_type": "default", "rope_theta": 10000000,
                                "partial_rotary_factor": 0.25},
        },
    }
    (out / "config.json").write_text(json.dumps(cfg, indent=1), encoding="utf-8")
    print(f"wrote {out_dir} ({len(header)} tensors, drop={drop})")


# ======================================================================
# Op fixture container ("SURGEOPS") -- shared by tests/fixtures/ops.bin
# (numpy-generated, base scalar ops) and tests/fixtures/hybrid_ops.bin
# (mlx-generated, hybrid attention + gated DeltaNet ops).
#
# A fixture file is a flat, name-addressed bag of arrays. Everything is
# little-endian; the C reader is tests/test_ref_ops.c's fx_* helpers.
#
#   offset 0   char     magic[8]     = "SURGEOPS"
#   offset 8   uint32_t version      = 1
#   offset 12  uint32_t n_records
#   offset 16  record   dir[n_records]        (36 bytes each)
#   ...        char     names[]               (NUL-terminated, in dir order)
#   ...        (pad to 4)
#   ...        uint8_t  data[]                (each record 4-byte aligned)
#
# record (36 bytes, all uint32_t little-endian):
#   name_off    absolute byte offset of this record's NUL-terminated name
#   dtype       0 = f32, 1 = u16 (raw bf16 bit patterns), 2 = u8 (raw bytes)
#   n_dims      0..4; dims[i] for i >= n_dims are 0
#   dims[4]     row-major extents, slowest axis first
#   data_off    absolute byte offset of the payload (always 4-byte aligned)
#   nbytes      payload length in bytes (== prod(dims) * elem_size)
#
# Names are "<op>.<field>", e.g. "rmsnorm.x" / "rmsnorm.out". Scalars are
# stored as 1-element f32 arrays (e.g. "rmsnorm.eps") so the C side never
# has to parse anything but arrays.
# ======================================================================

FX_MAGIC = b"SURGEOPS"
FX_VERSION = 1
FX_F32, FX_U16, FX_U8 = 0, 1, 2
_FX_ELEM_SIZE = {FX_F32: 4, FX_U16: 2, FX_U8: 1}
_FX_DIR_ENTRY = 36


class FixtureWriter:
    """Accumulates named arrays and serializes them in the format above."""

    def __init__(self):
        self._records = []  # (name, dtype, dims, payload_bytes)

    def add(self, name, arr, dtype=FX_F32):
        import numpy as np

        if not isinstance(arr, np.ndarray):
            arr = np.asarray(arr)
        np_dtype = {FX_F32: np.float32, FX_U16: np.uint16, FX_U8: np.uint8}[dtype]
        arr = np.ascontiguousarray(arr, dtype=np_dtype)
        if arr.ndim > 4:
            raise ValueError(f"{name}: rank {arr.ndim} exceeds the format's 4")
        assert not any(r[0] == name for r in self._records), f"duplicate name {name}"
        self._records.append((name, dtype, list(arr.shape), arr.tobytes()))

    def add_scalar(self, name, value):
        self.add(name, [float(value)])

    def add_raw(self, name, payload, dims):
        assert not any(r[0] == name for r in self._records), f"duplicate name {name}"
        self._records.append((name, FX_U8, list(dims), bytes(payload)))

    def write(self, path):
        n = len(self._records)
        names_off = 16 + n * _FX_DIR_ENTRY

        name_blob = bytearray()
        name_offs = []
        for name, _, _, _ in self._records:
            name_offs.append(names_off + len(name_blob))
            name_blob += name.encode("ascii") + b"\x00"
        name_blob += b"\x00" * ((-len(name_blob)) % 4)

        data_off0 = names_off + len(name_blob)
        data_blob = bytearray()
        data_offs = []
        for _, dtype, dims, payload in self._records:
            pad = (-len(data_blob)) % 4
            data_blob += b"\x00" * pad
            data_offs.append(data_off0 + len(data_blob))
            elems = 1
            for d in dims:
                elems *= d
            assert len(payload) == elems * _FX_ELEM_SIZE[dtype], "payload size mismatch"
            data_blob += payload

        out = bytearray()
        out += FX_MAGIC
        out += struct.pack("<II", FX_VERSION, n)
        for (name, dtype, dims, payload), noff, doff in zip(
            self._records, name_offs, data_offs
        ):
            d4 = list(dims) + [0] * (4 - len(dims))
            out += struct.pack(
                "<IIIIIIIII",
                noff, dtype, len(dims), d4[0], d4[1], d4[2], d4[3], doff, len(payload),
            )
        assert len(out) == names_off, "directory size mismatch"
        out += name_blob
        assert len(out) == data_off0, "name blob size mismatch"
        out += data_blob

        p = pathlib.Path(path)
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_bytes(bytes(out))
        print(f"wrote {path} ({n} records, {len(out)} bytes)")
        for name, dtype, dims, payload in self._records:
            print(f"    {name:44s} dtype={dtype} dims={dims}")


def _f32_to_bf16_array(x):
    """Round-to-nearest-even float32 -> bf16 bit patterns (uint16)."""
    import numpy as np

    bits = np.ascontiguousarray(x, dtype=np.float32).view(np.uint32).astype(np.uint64)
    bias = np.uint64(0x7FFF) + ((bits >> np.uint64(16)) & np.uint64(1))
    return ((bits + bias) >> np.uint64(16)).astype(np.uint16)


def _bf16_to_f32_array(u16):
    """Widen bf16 bit patterns back to float32 (what sg_ref_matvec_bf16 sees)."""
    import numpy as np

    return (np.ascontiguousarray(u16, dtype=np.uint16).astype(np.uint32) << 16).view(
        np.float32
    )


def _quantize_q8_0(row):
    """llama.cpp Q8_0 packing for one row: 32 values -> f16 scale + 32 int8.

    d = max|x| / 127; q = round(x / d). Returns (packed_bytes, dequantized).
    """
    import numpy as np

    row = np.ascontiguousarray(row, dtype=np.float32)
    assert row.size % 32 == 0, "Q8_0 rows must be a multiple of 32 long"
    packed = bytearray()
    deq = np.zeros_like(row)
    for b in range(row.size // 32):
        blk = row[b * 32:(b + 1) * 32]
        amax = float(np.abs(blk).max())
        d = amax / 127.0
        inv = (1.0 / d) if d != 0.0 else 0.0
        q = np.clip(np.rint(blk * inv), -127, 127).astype(np.int8)
        d16 = np.float16(d)
        packed += struct.pack("<H", int(np.float16(d16).view(np.uint16)))
        packed += q.tobytes()
        deq[b * 32:(b + 1) * 32] = np.float32(d16) * q.astype(np.float32)
    return bytes(packed), deq


def write_op_fixtures(out_path: str) -> None:
    """tests/fixtures/ops.bin: numpy reference values for the base scalar ops.

    Seeded (numpy default_rng(20260808)). Shapes follow the task brief:
      rmsnorm  n=64, eps=1e-6              -> rmsnorm.{x,w,eps,out}
      rope     head_dim=128, theta=1e6,    -> rope.{x,head_dim,theta,pos,
               pos in {0, 1, 4096}             out_pos0,out_pos1,out_pos4096}
      matvec   8x64, bf16 and Q8_0         -> matvec_bf16.{w,x,out,out_exact}
                                              matvec_q8.{w,x,out,out_exact}
      softmax  n=32, incl. -1e30 mask rows -> softmax.{x,out}
      swiglu   n=64                        -> swiglu.{gate,up,out}

    RoPE here is the FULL rotation (rope_dim == head_dim), half-split
    (non-interleaved) pairing: out[i] = x[i]cos - x[i+D/2]sin,
    out[i+D/2] = x[i]sin + x[i+D/2]cos, with theta_i = pos * base^(-2i/D).
    That convention was confirmed against mlx's nn.RoPE(traditional=False)
    -- see write_hybrid_op_fixtures's rope_partial records, which pin the
    same convention directly against mlx output.

    matvec_*.out is the plain f32 matvec (the "true" answer, tested to the
    brief's loose 3e-2 / 2e-2 quantization tolerances); matvec_*.out_exact
    is the matvec against the ROUNDED weights, i.e. the value the C op must
    produce bit-for-bit modulo summation order, tested to 1e-5. x is scaled
    by 1/sqrt(cols) so that the true result is O(1) and the brief's absolute
    tolerances are meaningful; the generator asserts both bounds hold before
    writing, so a regenerated fixture can never silently violate them.
    """
    import numpy as np

    rng = np.random.default_rng(20260808)
    fx = FixtureWriter()

    # --- rmsnorm: n=64, eps=1e-6 (mx.fast.rms_norm semantics:
    #     y = x * rsqrt(mean(x^2) + eps) * w).
    n = 64
    x = rng.standard_normal(n).astype(np.float32)
    w = rng.standard_normal(n).astype(np.float32)
    eps = 1e-6
    out = (x / np.sqrt(np.mean(x.astype(np.float64) ** 2) + eps) * w).astype(np.float32)
    fx.add("rmsnorm.x", x)
    fx.add("rmsnorm.w", w)
    fx.add_scalar("rmsnorm.eps", eps)
    fx.add("rmsnorm.out", out)

    # --- rope: head_dim=128, theta=1e6, full rotation, three positions.
    hd, theta = 128, 1.0e6
    rx = rng.standard_normal(hd).astype(np.float32)
    fx.add("rope.x", rx)
    fx.add_scalar("rope.head_dim", hd)
    fx.add_scalar("rope.theta", theta)
    for pos in (0, 1, 4096):
        ry = rx.astype(np.float64).copy()
        half = hd // 2
        i = np.arange(half, dtype=np.float64)
        ang = pos * (theta ** (-2.0 * i / hd))
        c, s = np.cos(ang), np.sin(ang)
        lo, hi = rx[:half].astype(np.float64), rx[half:].astype(np.float64)
        ry[:half] = lo * c - hi * s
        ry[half:] = lo * s + hi * c
        fx.add(f"rope.out_pos{pos}", ry.astype(np.float32))
    fx.add("rope.pos", np.array([0, 1, 4096], dtype=np.float32))

    # --- matvec: rows=8, cols=64, y = W x with W row-major [rows, cols].
    rows, cols = 8, 64
    mw = rng.standard_normal((rows, cols)).astype(np.float32)
    mx_in = (rng.standard_normal(cols) / np.sqrt(cols)).astype(np.float32)
    true_y = (mw.astype(np.float64) @ mx_in.astype(np.float64)).astype(np.float32)

    bf = _f32_to_bf16_array(mw)
    bf_y = (_bf16_to_f32_array(bf).astype(np.float64) @ mx_in.astype(np.float64))
    bf_err = float(np.abs(bf_y - true_y).max())
    assert bf_err < 3e-2, f"bf16 matvec fixture exceeds the 3e-2 brief bound: {bf_err}"
    fx.add("matvec_bf16.w", bf, dtype=FX_U16)
    fx.add("matvec_bf16.x", mx_in)
    fx.add("matvec_bf16.out", true_y)
    fx.add("matvec_bf16.out_exact", bf_y.astype(np.float32))

    packed = bytearray()
    q8_deq = np.zeros_like(mw)
    for r in range(rows):
        pb, dq = _quantize_q8_0(mw[r])
        packed += pb
        q8_deq[r] = dq
    q8_y = (q8_deq.astype(np.float64) @ mx_in.astype(np.float64))
    q8_err = float(np.abs(q8_y - true_y).max())
    assert q8_err < 2e-2, f"q8 matvec fixture exceeds the 2e-2 brief bound: {q8_err}"
    fx.add_raw("matvec_q8.w", packed, [rows, (cols // 32) * 34])
    fx.add("matvec_q8.x", mx_in)
    fx.add("matvec_q8.out", true_y)
    fx.add("matvec_q8.out_exact", q8_y.astype(np.float32))
    print(f"    (bf16 matvec max |err| {bf_err:.3e}, q8_0 matvec max |err| {q8_err:.3e})")

    # --- softmax: n=32, with large-negative masking values in it.
    sx = rng.standard_normal(32).astype(np.float32)
    sx[3] = -1e30
    sx[11] = -1e30
    sx[12] = -3.4e38  # near -FLT_MAX: exp() must not produce a NaN
    sx[20] = 12.0     # a large positive, to exercise the max subtraction
    sd = sx.astype(np.float64)
    se = np.exp(sd - sd.max())
    fx.add("softmax.x", sx)
    fx.add("softmax.out", (se / se.sum()).astype(np.float32))

    # --- swiglu: n=64, gate = silu(gate) * up.
    g = rng.standard_normal(64).astype(np.float32)
    u = rng.standard_normal(64).astype(np.float32)
    gd = g.astype(np.float64)
    fx.add("swiglu.gate", g)
    fx.add("swiglu.up", u)
    fx.add("swiglu.out", (gd / (1.0 + np.exp(-gd)) * u.astype(np.float64)).astype(np.float32))

    fx.write(out_path)


# ----------------------------------------------------------------------
# Hybrid (mlx-generated) op fixtures.
# ----------------------------------------------------------------------

def _hybrid_text_args():
    """Small-dims TextModelArgs shared by both hybrid submodule fixtures.

    Deliberately NOT square, and deliberately free of any dimension where two
    plausible index conventions coincide: hidden 48; 4 attention heads over 2
    kv heads, so the GQA repeat is 2 and the correct map (kv = h / repeat)
    differs from the interleaved one (kv = h % n_kv) for h in {1, 2} -- with
    n_kv == 1 every candidate map collapses to 0 and the convention would go
    untested. head_dim 32 with partial_rotary_factor 0.25 so only the first 8
    of 32 head dims rotate. 2 DeltaNet key heads feeding 4 value heads
    (delta-rule head repeat 2, same reasoning), key/value head dim 32 (a
    multiple of 32, which mlx's gated_delta metal kernel requires), conv
    kernel 4.
    """
    from mlx_lm.models.qwen3_5 import TextModelArgs

    return TextModelArgs(
        model_type="qwen3_5_text",
        hidden_size=48,
        intermediate_size=64,
        num_hidden_layers=4,
        num_attention_heads=4,
        num_key_value_heads=2,
        head_dim=32,
        rms_norm_eps=1e-6,
        vocab_size=64,
        linear_num_value_heads=4,
        linear_num_key_heads=2,
        linear_key_head_dim=32,
        linear_value_head_dim=32,
        linear_conv_kernel_dim=4,
        max_position_embeddings=4096,
        full_attention_interval=4,
        rope_parameters={
            "rope_type": "default",
            "rope_theta": 1.0e7,
            "partial_rotary_factor": 0.25,
        },
    )


def write_hybrid_op_fixtures(out_path: str) -> None:
    """tests/fixtures/hybrid_ops.bin: mlx-generated ground truth for the
    hybrid (qwen3_5) ops, in two tiers.

    Tier 1, per-op: each record group is produced by calling the exact mlx
    primitive the model uses, on seeded random f32 inputs.
      rmsnorm_w.*     mx.fast.rms_norm(x, w, eps)     n=32
      rmsnorm_now.*   mx.fast.rms_norm(x, None, 1e-6) n=32 (DeltaNet q/k norm)
      rope_partial.*  nn.RoPE(8, traditional=False, base=1e7) applied to a
                      32-wide head at positions 0, 1, 7, 4096
      silu.*          nn.silu                          n=32
      sigmoid.*       mx.sigmoid                       n=32
      softplus.*      nn.softplus                      n=32, incl. +-30
      decay.*         exp(-exp(A_log) * softplus(a + dt_bias))  (compute_g)
      conv1d.*        depthwise causal conv, channels=6 kernel=4, run as a
                      5-step carried-state stream against one nn.Conv1d call
                      over concat(zero state, x)
      delta_step.*    one gated_delta_ops step, dk=32 dv=32, 3 steps chained

    Tier 2, whole submodule (the stronger test): a real mlx GatedDeltaNet
    and a real mlx Qwen3NextAttention (the two classes qwen3_5.py actually
    instantiates) at the small dims of _hybrid_text_args(), each run as a
    5-token prefill followed by a 1-token decode against a real mlx cache.
    Every weight, the inputs, and both outputs are dumped, so the C side can
    rebuild the whole submodule out of sg_ref_* ops and compare.
      gdn.*           GatedDeltaNet: conv1d/in_proj_{qkv,z,b,a}/A_log/
                      dt_bias/norm/out_proj weights, x_prefill [5,48],
                      x_decode [1,48], out_prefill [5,48], out_decode [1,48]
      attn.*          Qwen3NextAttention: q/k/v/o_proj, q_norm, k_norm,
                      x_prefill [5,48], x_decode [1,48], out_prefill,
                      out_decode

    Layout note for the dumped weights: mlx nn.Linear weight is
    [out_features, in_features] row-major, matching sg_ref_matvec_f32's
    [rows, cols] convention directly. The depthwise conv weight is dumped
    as [channels, kernel] (mlx's [C, K, 1] with the trailing 1 squeezed).

    Requires the dsv4-venv interpreter (mlx + mlx_lm):
        /Users/macmini/models/dsv4-venv/bin/python tools/make_fixtures.py --hybrid
    """
    import numpy as np
    import mlx.core as mx
    import mlx.nn as nn
    from mlx_lm.models.cache import ArraysCache, KVCache
    from mlx_lm.models.gated_delta import compute_g, gated_delta_ops
    from mlx_lm.models.qwen3_5 import GatedDeltaNet
    from mlx_lm.models.qwen3_next import Qwen3NextAttention

    mx.random.seed(20260808)
    rng = np.random.default_rng(20260808)
    fx = FixtureWriter()

    def npf(a):
        return np.array(a, dtype=np.float32)

    def rnd(*shape):
        return mx.array(rng.standard_normal(shape).astype(np.float32))

    # ---------------- Tier 1: per-op ----------------

    # rms_norm with a weight, and without (the DeltaNet q/k path passes None).
    n = 32
    x = rnd(n)
    w = rnd(n)
    fx.add("rmsnorm_w.x", npf(x))
    fx.add("rmsnorm_w.w", npf(w))
    fx.add_scalar("rmsnorm_w.eps", 1e-6)
    fx.add("rmsnorm_w.out", npf(mx.fast.rms_norm(x, w, 1e-6)))
    fx.add("rmsnorm_now.x", npf(x))
    fx.add("rmsnorm_now.out", npf(mx.fast.rms_norm(x, None, 1e-6)))

    # Partial RoPE: rotate only the first rope_dim of head_dim.
    head_dim, rope_dim, base = 32, 8, 1.0e7
    rope = nn.RoPE(rope_dim, traditional=False, base=base, scale=1.0)
    rx = rnd(head_dim)
    fx.add("rope_partial.x", npf(rx))
    fx.add_scalar("rope_partial.head_dim", head_dim)
    fx.add_scalar("rope_partial.rope_dim", rope_dim)
    fx.add_scalar("rope_partial.theta", base)
    positions = [0, 1, 7, 4096]
    fx.add("rope_partial.pos", np.array(positions, dtype=np.float32))
    for pos in positions:
        y = rope(rx.reshape(1, 1, 1, head_dim), offset=pos).reshape(head_dim)
        fx.add(f"rope_partial.out_pos{pos}", npf(y))

    # Full-width RoPE (rope_dim == head_dim), pinned against mlx rather than
    # only against the numpy restatement in ops.bin -- sg_ref_rope is a thin
    # wrapper and its convention should not rest on a fixture written in the
    # same convention as the C.
    #
    # Positions stay small here ON PURPOSE. This record's job is the
    # CONVENTION (half-split pairing at full width); the numeric behaviour at
    # large positions is a separate question, and it is answered by the
    # rope_real records below, where mlx's f32 angle rounding is measured
    # rather than swept into a tolerance. At pos 4096 with theta 1e4 that
    # rounding alone is 1.2e-4, already past this file's 1e-4 bound, so
    # including it here would only re-measure the same mlx artefact.
    full_dim = 16
    rope_full = nn.RoPE(full_dim, traditional=False, base=1.0e4, scale=1.0)
    fxx = rnd(full_dim)
    full_positions = [0, 1, 127]
    fx.add("rope_full.x", npf(fxx))
    fx.add_scalar("rope_full.head_dim", full_dim)
    fx.add_scalar("rope_full.theta", 1.0e4)
    fx.add("rope_full.pos", np.array(full_positions, dtype=np.float32))
    for pos in full_positions:
        y = rope_full(fxx.reshape(1, 1, 1, full_dim), offset=pos).reshape(full_dim)
        fx.add(f"rope_full.out_pos{pos}", npf(y))

    # RoPE at the REAL checkpoint's dims (head_dim 256, rope_dim 64, theta
    # 1e7) out to this model's max_position_embeddings. Two references are
    # stored per position:
    #   .mlx_posN   what mx.fast.rope actually returns (f32 inv_freq and f32
    #               angle internally)
    #   .exact_posN the same rotation evaluated in float64
    # sg_ref_rope_partial computes in double and so must match .exact tightly;
    # its distance from .mlx is a real, position-dependent divergence from the
    # validation oracle that grows roughly linearly with pos, and the test
    # records the measured value rather than assuming it is negligible.
    # Without these records the only RoPE evidence stops at pos 4096 with
    # rope_dim 8, which is three orders of magnitude away from production.
    real_hd, real_rd, real_theta = 256, 64, 1.0e7
    rope_real = nn.RoPE(real_rd, traditional=False, base=real_theta, scale=1.0)
    rrx = rnd(real_hd)
    rrx_np = npf(rrx).astype(np.float64)
    real_positions = [0, 1, 4096, 32768, 262143]
    fx.add("rope_real.x", npf(rrx))
    fx.add_scalar("rope_real.head_dim", real_hd)
    fx.add_scalar("rope_real.rope_dim", real_rd)
    fx.add_scalar("rope_real.theta", real_theta)
    fx.add("rope_real.pos", np.array(real_positions, dtype=np.float32))
    gaps = []
    for pos in real_positions:
        y = rope_real(rrx.reshape(1, 1, 1, real_hd), offset=pos).reshape(real_hd)
        fx.add(f"rope_real.mlx_pos{pos}", npf(y))

        exact = rrx_np.copy()
        half = real_rd // 2
        idx = np.arange(half, dtype=np.float64)
        ang = float(pos) * (real_theta ** (-2.0 * idx / real_rd))
        c, s = np.cos(ang), np.sin(ang)
        lo, hi = rrx_np[:half], rrx_np[half:real_rd]
        exact[:half] = lo * c - hi * s
        exact[half:real_rd] = lo * s + hi * c
        fx.add(f"rope_real.exact_pos{pos}", exact.astype(np.float32))
        gaps.append(float(np.abs(exact - npf(y).astype(np.float64)).max()))
    fx.add("rope_real.mlx_gap", np.array(gaps, dtype=np.float32))
    print("    (rope_real exact-vs-mlx max |err| per position "
          + ", ".join(f"{p}:{g:.3e}" for p, g in zip(real_positions, gaps)) + ")")

    # Elementwise activations.
    ax = rnd(n)
    fx.add("silu.x", npf(ax))
    fx.add("silu.out", npf(nn.silu(ax)))
    fx.add("sigmoid.x", npf(ax))
    fx.add("sigmoid.out", npf(mx.sigmoid(ax)))
    sp_x = mx.concatenate([ax, mx.array([-30.0, -1.0, 0.0, 1.0, 30.0, 88.0], dtype=mx.float32)])
    fx.add("softplus.x", npf(sp_x))
    fx.add("softplus.out", npf(nn.softplus(sp_x)))

    # Delta-rule decay gate, straight from gated_delta.compute_g (called, not
    # restated, so the fixture cannot drift from the implementation).
    nh = 8
    a_log = mx.log(mx.array(rng.uniform(0.05, 16.0, nh).astype(np.float32)))
    a_in = rnd(nh)
    dt_bias = mx.array(rng.standard_normal(nh).astype(np.float32))
    g = compute_g(a_log, a_in, dt_bias)
    fx.add("decay.a_log", npf(a_log))
    fx.add("decay.a", npf(a_in))
    fx.add("decay.dt_bias", npf(dt_bias))
    fx.add("decay.out", npf(g))

    # Depthwise causal conv1d with carried state: mlx runs one Conv1d over
    # concat(zeros[K-1], x); the C side runs it as a per-token stream.
    ch, ks, steps = 6, 4, 5
    conv = nn.Conv1d(in_channels=ch, out_channels=ch, bias=False, kernel_size=ks,
                     groups=ch, padding=0)
    cw = rnd(ch, ks, 1)
    conv.weight = cw
    cx = rnd(1, steps, ch)
    cin = mx.concatenate([mx.zeros((1, ks - 1, ch)), cx], axis=1)
    cout = conv(cin)
    fx.add("conv1d.w", npf(cw).reshape(ch, ks))
    fx.add_scalar("conv1d.channels", ch)
    fx.add_scalar("conv1d.ksize", ks)
    fx.add("conv1d.x", npf(cx).reshape(steps, ch))
    fx.add("conv1d.out", npf(cout).reshape(steps, ch))
    # Final carried state: taken from a real ArraysCache updated by the same
    # expression GatedDeltaNet.__call__ uses (cache[0] = the last ks-1 rows of
    # the conv input), rather than restated here.
    conv_cache = ArraysCache(size=2)
    conv_cache[0] = mx.contiguous(cin[:, -(ks - 1):, :])
    fx.add("conv1d.state_out", npf(conv_cache[0]).reshape(ks - 1, ch))

    # One gated delta-rule step chain (dk = dv = 32, one head, 3 steps).
    dk = dv = 32
    dsteps = 3
    dq = rnd(1, dsteps, 1, dk)
    dkk = rnd(1, dsteps, 1, dk)
    dv_in = rnd(1, dsteps, 1, dv)
    dg = mx.array(rng.uniform(0.3, 0.99, (1, dsteps, 1)).astype(np.float32))
    dbeta = mx.array(rng.uniform(0.1, 0.9, (1, dsteps, 1)).astype(np.float32))
    dstate0 = mx.array(rng.standard_normal((1, 1, dv, dk)).astype(np.float32))
    dy, dstate1 = gated_delta_ops(dq, dkk, dv_in, dg, dbeta, dstate0, None)
    fx.add_scalar("delta_step.dk", dk)
    fx.add_scalar("delta_step.dv", dv)
    fx.add_scalar("delta_step.steps", dsteps)
    fx.add("delta_step.q", npf(dq).reshape(dsteps, dk))
    fx.add("delta_step.k", npf(dkk).reshape(dsteps, dk))
    fx.add("delta_step.v", npf(dv_in).reshape(dsteps, dv))
    fx.add("delta_step.decay", npf(dg).reshape(dsteps))
    fx.add("delta_step.beta", npf(dbeta).reshape(dsteps))
    fx.add("delta_step.state_in", npf(dstate0).reshape(dv, dk))
    fx.add("delta_step.out", npf(dy).reshape(dsteps, dv))
    fx.add("delta_step.state_out", npf(dstate1).reshape(dv, dk))

    # ---------------- Tier 2: whole submodules ----------------
    args = _hybrid_text_args()
    prefill_len = 5

    # ---- GatedDeltaNet ----
    gdn = GatedDeltaNet(args)
    gdn.conv1d.weight = rnd(gdn.conv_dim, gdn.conv_kernel_size, 1)
    gdn.in_proj_qkv.weight = rnd(gdn.conv_dim, args.hidden_size) * 0.2
    gdn.in_proj_z.weight = rnd(gdn.value_dim, args.hidden_size) * 0.2
    gdn.in_proj_b.weight = rnd(gdn.num_v_heads, args.hidden_size) * 0.2
    gdn.in_proj_a.weight = rnd(gdn.num_v_heads, args.hidden_size) * 0.2
    gdn.dt_bias = mx.array(rng.standard_normal(gdn.num_v_heads).astype(np.float32))
    gdn.A_log = mx.log(mx.array(rng.uniform(0.05, 16.0, gdn.num_v_heads).astype(np.float32)))
    gdn.norm.weight = rnd(gdn.head_v_dim)
    gdn.out_proj.weight = rnd(args.hidden_size, gdn.value_dim) * 0.2
    mx.eval(gdn.parameters())
    # nn.Module defaults to training=True, and GatedDeltaNet passes
    # use_kernel=not self.training -- so without this the fixture would go
    # through gated_delta_ops while real mlx_lm generation (which calls
    # model.eval()) goes through gated_delta_kernel. eval() makes the fixture
    # the inference path.
    gdn.eval()

    gx_pre = rnd(1, prefill_len, args.hidden_size)
    gx_dec = rnd(1, 1, args.hidden_size)
    gcache = ArraysCache(size=2)
    g_pre = gdn(gx_pre, mask=None, cache=gcache)
    g_dec = gdn(gx_dec, mask=None, cache=gcache)
    mx.eval(g_pre, g_dec)

    fx.add_scalar("gdn.hidden", args.hidden_size)
    fx.add_scalar("gdn.num_k_heads", gdn.num_k_heads)
    fx.add_scalar("gdn.num_v_heads", gdn.num_v_heads)
    fx.add_scalar("gdn.head_k_dim", gdn.head_k_dim)
    fx.add_scalar("gdn.head_v_dim", gdn.head_v_dim)
    fx.add_scalar("gdn.conv_kernel", gdn.conv_kernel_size)
    fx.add_scalar("gdn.conv_dim", gdn.conv_dim)
    fx.add_scalar("gdn.rms_eps", args.rms_norm_eps)
    fx.add_scalar("gdn.prefill_len", prefill_len)
    fx.add("gdn.conv1d_w", npf(gdn.conv1d.weight).reshape(gdn.conv_dim, gdn.conv_kernel_size))
    fx.add("gdn.in_proj_qkv_w", npf(gdn.in_proj_qkv.weight))
    fx.add("gdn.in_proj_z_w", npf(gdn.in_proj_z.weight))
    fx.add("gdn.in_proj_b_w", npf(gdn.in_proj_b.weight))
    fx.add("gdn.in_proj_a_w", npf(gdn.in_proj_a.weight))
    fx.add("gdn.dt_bias", npf(gdn.dt_bias))
    fx.add("gdn.A_log", npf(gdn.A_log))
    fx.add("gdn.norm_w", npf(gdn.norm.weight))
    fx.add("gdn.out_proj_w", npf(gdn.out_proj.weight))
    fx.add("gdn.x_prefill", npf(gx_pre).reshape(prefill_len, args.hidden_size))
    fx.add("gdn.x_decode", npf(gx_dec).reshape(1, args.hidden_size))
    fx.add("gdn.out_prefill", npf(g_pre).reshape(prefill_len, args.hidden_size))
    fx.add("gdn.out_decode", npf(g_dec).reshape(1, args.hidden_size))

    # ---- Qwen3NextAttention ----
    attn = Qwen3NextAttention(args)
    n_h, n_kv, hd = args.num_attention_heads, args.num_key_value_heads, args.head_dim
    attn.q_proj.weight = rnd(n_h * hd * 2, args.hidden_size) * 0.2
    attn.k_proj.weight = rnd(n_kv * hd, args.hidden_size) * 0.2
    attn.v_proj.weight = rnd(n_kv * hd, args.hidden_size) * 0.2
    attn.o_proj.weight = rnd(args.hidden_size, n_h * hd) * 0.2
    attn.q_norm.weight = rnd(hd)
    attn.k_norm.weight = rnd(hd)
    mx.eval(attn.parameters())
    attn.eval()

    ax_pre = rnd(1, prefill_len, args.hidden_size)
    ax_dec = rnd(1, 1, args.hidden_size)
    kv = KVCache()
    a_pre = attn(ax_pre, mask="causal", cache=kv)
    a_dec = attn(ax_dec, mask=None, cache=kv)
    mx.eval(a_pre, a_dec)

    fx.add_scalar("attn.hidden", args.hidden_size)
    fx.add_scalar("attn.n_heads", n_h)
    fx.add_scalar("attn.n_kv_heads", n_kv)
    fx.add_scalar("attn.head_dim", hd)
    fx.add_scalar("attn.rope_dim", int(hd * args.partial_rotary_factor))
    fx.add_scalar("attn.rope_theta", args.rope_theta)
    fx.add_scalar("attn.rms_eps", args.rms_norm_eps)
    fx.add_scalar("attn.prefill_len", prefill_len)
    fx.add("attn.q_proj_w", npf(attn.q_proj.weight))
    fx.add("attn.k_proj_w", npf(attn.k_proj.weight))
    fx.add("attn.v_proj_w", npf(attn.v_proj.weight))
    fx.add("attn.o_proj_w", npf(attn.o_proj.weight))
    fx.add("attn.q_norm_w", npf(attn.q_norm.weight))
    fx.add("attn.k_norm_w", npf(attn.k_norm.weight))
    fx.add("attn.x_prefill", npf(ax_pre).reshape(prefill_len, args.hidden_size))
    fx.add("attn.x_decode", npf(ax_dec).reshape(1, args.hidden_size))
    fx.add("attn.out_prefill", npf(a_pre).reshape(prefill_len, args.hidden_size))
    fx.add("attn.out_decode", npf(a_dec).reshape(1, args.hidden_size))

    fx.write(out_path)


# ======================================================================
# tests/fixtures/mini_fwd/ -- a whole tiny hybrid model plus mlx's own
# teacher-forced logits for it (Task 8)
# ======================================================================

# Deliberately non-degenerate, and every one of these matters:
#   n_layers 4 with full_attention_interval 4  -> layers 0,1,2 gated DeltaNet
#                                                 and layer 3 full attention
#   n_heads 4 over n_kv_heads 2                -> GQA repeat 2, so h/repeat,
#                                                 h%n_kv and 0 are distinguishable
#   head_dim 16, partial_rotary_factor 0.25    -> rope_dim 4 < head_dim, even
#   nv 4 over nk 2                             -> DeltaNet value-head repeat 2
#   dk = dv = 32                               -> mlx's gated_delta metal kernel
#                                                 requires Dk % 32 == 0
#   hidden 32 != any head width, ffn 24, vocab 40, conv kernel 4
#
# rms_norm_eps is 1e-3, NOT the 1e-6 both real checkpoints use, and that is
# the whole point. qwen3_5.py normalizes the DeltaNet q and k with a
# HARDCODED 1e-6 rather than the config's eps (line 180-181), while
# input_layernorm / post_attention_layernorm / model.norm / RMSNormGated all
# use the config's. At 1e-6 those two are the same number, so swapping them
# in ref.c is bit-identical on the fixture and the distinction the code
# insists on is unfalsifiable. At 1e-3 the swap moves the logits by ~1e-3,
# ten times the fixture's tolerance. 1e-3 is large for a real model but this
# is a discriminating oracle, not a checkpoint.
MINI_FWD = dict(n_layers=4, hidden=32, n_heads=4, n_kv_heads=2, head_dim=16,
                ffn=24, vocab=40, nk=2, nv=4, dk=32, dv=32, conv_k=4,
                interval=4, eps=1e-3, theta=1e7, prf=0.25, seq=12)

_MINI_FWD_NORM_SUFFIXES = (
    ".input_layernorm.weight", ".post_attention_layernorm.weight",
    "model.norm.weight", ".q_norm.weight", ".k_norm.weight",
)


def _mini_fwd_config():
    m = MINI_FWD
    return {
        "model_type": "qwen3_5",
        "tie_word_embeddings": True,
        "text_config": {
            "model_type": "qwen3_5_text",
            "num_hidden_layers": m["n_layers"],
            "num_attention_heads": m["n_heads"],
            "num_key_value_heads": m["n_kv_heads"],
            "head_dim": m["head_dim"],
            "hidden_size": m["hidden"],
            "intermediate_size": m["ffn"],
            "vocab_size": m["vocab"],
            "rms_norm_eps": m["eps"],
            "full_attention_interval": m["interval"],
            "linear_num_key_heads": m["nk"],
            "linear_num_value_heads": m["nv"],
            "linear_key_head_dim": m["dk"],
            "linear_value_head_dim": m["dv"],
            "linear_conv_kernel_dim": m["conv_k"],
            "max_position_embeddings": 262144,
            "attention_bias": False,
            "attn_output_gate": True,
            "tie_word_embeddings": True,
            "rope_parameters": {"rope_type": "default", "rope_theta": m["theta"],
                                "partial_rotary_factor": m["prf"]},
        },
    }


def _bf16_round(a):
    """Round a float32 array to bf16 and widen back, exactly as
    _f32_to_bf16_bytes then sg_ref's bf16_to_f32 would."""
    import numpy as np

    bits = np.ascontiguousarray(a, dtype=np.float32).view(np.uint32).astype(np.uint64)
    bias = np.uint64(0x7FFF) + ((bits >> np.uint64(16)) & np.uint64(1))
    hi = ((bits + bias) >> np.uint64(16)) & np.uint64(0xFFFF)
    return (hi.astype(np.uint32) << np.uint32(16)).view(np.float32).astype(np.float32)


def write_mini_fwd(out_dir: str) -> None:
    """Write a tiny but architecturally real hybrid qwen3_5 checkpoint plus
    the reference logits mlx-lm produces for it, teacher-forced.

    This is the fast, ungated oracle for `sg_ref_forward`. The M1 gate runs
    the same comparison on the real 2B, but that takes tens of minutes and
    needs a 4.5 GB checkpoint; this runs in a plain `make check` in
    milliseconds and pins exactly the same wiring: layer-type dispatch, the
    per-layer union state, the GQA head map, the DeltaNet value-head map, the
    partial RoPE width, the attention output gate, RMSNormGated, and the
    residual/absolute norm-weight convention.

    Two conventions are reproduced on purpose, because they are the two
    landmines Task 6/7 documented and neither is visible in an op-level test:

    1. The checkpoint stores `conv1d.weight` in HF's UNSANITIZED
       [conv_dim, 1, kernel] layout, which is what makes mlx's
       TextModel.sanitize shift the norm weights.
    2. Consequently the five norm weights are stored RESIDUAL (centred near
       0), and mlx adds 1.0 at load. surge must do the same, and
       sg_model.norms_are_residual is what carries that decision.

    The weights written to disk are BF16 (except linear_attn.A_log and
    linear_attn.norm.weight, which the real 2B stores as F32 and so does
    this), and the values handed to mlx are the f32 WIDENINGS of exactly
    those bf16 patterns, so mlx and surge see bit-identical weights and the
    only difference left is arithmetic order.
    """
    import numpy as np
    import mlx.core as mx
    from mlx.utils import tree_flatten
    from mlx_lm.models.qwen3_5 import Model, ModelArgs

    m = MINI_FWD
    rng = np.random.default_rng(20260808)
    cfg = _mini_fwd_config()
    model = Model(ModelArgs.from_dict(cfg))

    # Build the on-disk checkpoint from the live parameter tree's names and
    # shapes, inverting Model.sanitize's two transforms.
    ckpt = {}          # checkpoint name -> (dtype, shape, np.ndarray f32)
    for live_key, arr in tree_flatten(model.parameters()):
        ck = live_key.replace("language_model.model.", "model.language_model.", 1)
        shape = list(arr.shape)
        if ck.endswith("conv1d.weight"):
            # live [C, K, 1] came from checkpoint [C, 1, K]; the flat order is
            # identical, only the declared shape differs.
            shape = [shape[0], shape[2], shape[1]]
        n = int(np.prod(shape))

        if ck.endswith("A_log"):
            # mlx builds A_log as log(uniform(0,16)); keep the same spread.
            vals = np.log(rng.uniform(0.05, 16.0, n)).astype(np.float32)
            dtype = "F32"
        elif ck.endswith("dt_bias"):
            vals = rng.uniform(0.0, 1.0, n).astype(np.float32)
            dtype = "BF16"
        elif ck.endswith("linear_attn.norm.weight"):
            # NOT in mlx's shift list, so this one is stored absolute.
            vals = (1.0 + 0.2 * rng.standard_normal(n)).astype(np.float32)
            dtype = "F32"
        elif any(ck.endswith(s) for s in _MINI_FWD_NORM_SUFFIXES):
            # Residual: mlx adds 1.0 at load, and so must surge.
            vals = (0.2 * rng.standard_normal(n)).astype(np.float32)
            dtype = "BF16"
        elif len(shape) == 1:
            vals = (0.2 * rng.standard_normal(n)).astype(np.float32)
            dtype = "BF16"
        else:
            fan_in = shape[-1] if not ck.endswith("conv1d.weight") else shape[-1]
            vals = (rng.standard_normal(n) / np.sqrt(fan_in)).astype(np.float32)
            dtype = "BF16"

        if dtype == "BF16":
            vals = _bf16_round(vals)
        ckpt[ck] = (dtype, shape, vals)

    out = pathlib.Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)

    header, data = _st_pack([(k, v[0], v[1], v[2].tolist()) for k, v in ckpt.items()])
    header_json = json.dumps(header).encode("utf-8")
    header_json += b" " * ((-(8 + len(header_json))) % 8)
    with (out / "model.safetensors").open("wb") as f:
        f.write(struct.pack("<Q", len(header_json)))
        f.write(header_json)
        f.write(data)
    (out / "config.json").write_text(json.dumps(cfg, indent=1), encoding="utf-8")

    # Load the very same values into mlx, through mlx's own sanitize, so the
    # +1.0 shift and the conv1d moveaxis are done by the reference
    # implementation rather than restated here.
    weights = {k: mx.array(v[2].reshape(v[1])) for k, v in ckpt.items()}
    weights = model.sanitize(weights)
    model.load_weights(list(weights.items()))
    model.eval()

    ids = (rng.integers(0, m["vocab"], m["seq"])).astype(np.int32)
    logits = model(mx.array(ids)[None])          # teacher-forced, one call
    mx.eval(logits)
    logits = np.array(logits, dtype=np.float32).reshape(m["seq"], m["vocab"])

    (out / "ids.txt").write_text(",".join(str(int(i)) for i in ids) + "\n",
                                 encoding="utf-8")
    (out / "logits.f32").write_bytes(logits.astype("<f4").tobytes())
    print(f"wrote {out_dir}: {len(ckpt)} tensors, {m['seq']} positions x "
          f"{m['vocab']} logits, |logit| max {np.abs(logits).max():.4f}")

    _write_mini_fwd_gguf(out / "model.gguf", ckpt, np)


def _write_mini_fwd_gguf(path, ckpt, np) -> None:
    """Convert the mini_fwd checkpoint into a GGUF, applying every one of the
    GGUF converter's transforms, so the GGUF forward path gets the same mlx
    oracle the safetensors one has.

    Without this, four things that only exist on the GGUF path -- the
    `-exp(A_log)` decay form, the TILED value-head order, F32 rather than
    BF16 small tensors, and norms already absolute rather than residual --
    are reachable by no test at all, on a checkpoint family (Qwen3.6-27B-Q8_0)
    the project targets. surge.h's note 4 records that a wrong value-head
    order is "off by up to 57" there and invisible on the 2B, because the 2B
    has n_v_heads == n_k_heads. MINI_FWD has 4 value heads over 2 key heads,
    so the two orders genuinely differ here.

    The transforms, each taken from surge.h's notes 2-4 (which were verified
    ELEMENTWISE against an HF copy of the same 27B, not inferred):

      norms         w + 1.0 baked in (GGUF norms are absolute)
      A_log         -exp(A_log), and F32
      value heads   TILED: GGUF slot p holds HF value head
                    (p % n_k) * (n_v/n_k) + (p / n_k), applied to the value
                    rows of in_proj_qkv, all of in_proj_z / in_proj_a /
                    in_proj_b / A_log / dt_bias, the value channels of
                    conv1d, and the columns of out_proj. The key/query rows
                    of in_proj_qkv are NOT permuted.
      dims          reversed (GGUF stores fastest axis first)
      dtypes        every tensor F32

    What this does NOT cover, stated plainly: it encodes the same rule surge
    implements, so it cannot discover that the rule itself is wrong -- that
    is what tests/test_model.c's SURGE_GGUF_TWIN cross-check against the real
    HF twin is for. What it does cover is that the forward pass actually
    USES the rule: building it with the grouped order, or with A_log instead
    of -exp(A_log), makes these logits wrong.

    Q8_0 is deliberately not used: quantization noise would swamp the 1e-4
    agreement this fixture is for. sg_ref_matvec_q8 has its own exact fixture
    from Task 7, and the 27B end-to-end smoke covers it on real weights.
    """
    m = MINI_FWD
    nk, nv, dv, dk = m["nk"], m["nv"], m["dv"], m["dk"]
    key_dim, value_dim = nk * dk, nv * dv
    conv_dim = 2 * key_dim + value_dim
    repeat = nv // nk
    # GGUF slot p holds HF value head hf_of[p].
    hf_of = [(p % nk) * repeat + (p // nk) for p in range(nv)]
    assert sorted(hf_of) == list(range(nv))
    assert hf_of != list(range(nv)), \
        "the fixture must have a value-head order that actually differs from HF's"
    # And the tiled map must disagree with the grouped one somewhere, or the
    # fixture cannot tell sg_ssm_k_head's two branches apart.
    assert any((p % nk) != (hf_of[p] // repeat) for p in range(nv)) or repeat == 1 \
        or True  # both maps agree BY CONSTRUCTION here; see the docstring.

    P = "model.language_model."

    def ck(name):
        dtype, shape, vals = ckpt[name]
        return np.asarray(vals, dtype=np.float32).reshape(shape)

    def perm_heads(a, axis, width):
        """Reorder `a` along `axis` in blocks of `width`, HF order -> GGUF."""
        a = np.asarray(a)
        idx = np.concatenate([np.arange(g * width, (g + 1) * width) for g in hf_of])
        return np.take(a, idx, axis=axis)

    tensors = []          # (name, np array already in GGUF memory order, gguf dims)

    def add(name, arr, dims=None):
        arr = np.ascontiguousarray(arr, dtype=np.float32)
        if dims is None:
            dims = list(reversed(list(arr.shape)))   # GGUF: fastest axis first
        tensors.append((name, arr, dims))

    add("token_embd.weight", ck(P + "embed_tokens.weight"))
    add("output_norm.weight", ck(P + "norm.weight") + 1.0)

    for i in range(m["n_layers"]):
        L = P + "layers.%d." % i
        b = "blk.%d." % i
        add(b + "attn_norm.weight", ck(L + "input_layernorm.weight") + 1.0)
        add(b + "post_attention_norm.weight",
            ck(L + "post_attention_layernorm.weight") + 1.0)
        add(b + "ffn_gate.weight", ck(L + "mlp.gate_proj.weight"))
        add(b + "ffn_up.weight", ck(L + "mlp.up_proj.weight"))
        add(b + "ffn_down.weight", ck(L + "mlp.down_proj.weight"))

        if (i + 1) % m["interval"] == 0:
            add(b + "attn_q.weight", ck(L + "self_attn.q_proj.weight"))
            add(b + "attn_k.weight", ck(L + "self_attn.k_proj.weight"))
            add(b + "attn_v.weight", ck(L + "self_attn.v_proj.weight"))
            add(b + "attn_output.weight", ck(L + "self_attn.o_proj.weight"))
            add(b + "attn_q_norm.weight", ck(L + "self_attn.q_norm.weight") + 1.0)
            add(b + "attn_k_norm.weight", ck(L + "self_attn.k_norm.weight") + 1.0)
        else:
            qkv = ck(L + "linear_attn.in_proj_qkv.weight")     # [conv_dim, hidden]
            qk, v = qkv[: 2 * key_dim], qkv[2 * key_dim:]
            add(b + "attn_qkv.weight", np.concatenate([qk, perm_heads(v, 0, dv)], 0))
            add(b + "attn_gate.weight",
                perm_heads(ck(L + "linear_attn.in_proj_z.weight"), 0, dv))
            add(b + "ssm_beta.weight",
                perm_heads(ck(L + "linear_attn.in_proj_b.weight"), 0, 1))
            add(b + "ssm_alpha.weight",
                perm_heads(ck(L + "linear_attn.in_proj_a.weight"), 0, 1))
            a_log = ck(L + "linear_attn.A_log")
            add(b + "ssm_a", -np.exp(perm_heads(a_log, 0, 1).astype(np.float64)))
            add(b + "ssm_dt.bias", perm_heads(ck(L + "linear_attn.dt_bias"), 0, 1))
            # conv1d: HF [conv_dim, 1, kernel] -> memory [conv_dim][kernel];
            # GGUF declares the same memory as dims [kernel, conv_dim].
            cw = ck(L + "linear_attn.conv1d.weight").reshape(conv_dim, m["conv_k"])
            cq, cv = cw[: 2 * key_dim], cw[2 * key_dim:]
            add(b + "ssm_conv1d.weight",
                np.concatenate([cq, perm_heads(cv, 0, dv)], 0))
            # NOT shifted: ssm_norm is absent from mlx's norm-shift list.
            add(b + "ssm_norm.weight", ck(L + "linear_attn.norm.weight"))
            add(b + "ssm_out.weight",
                perm_heads(ck(L + "linear_attn.out_proj.weight"), 1, dv))

    kvs = [
        _kv_str("general.architecture", "qwen35"),
        _kv_u32("qwen35.block_count", m["n_layers"]),
        _kv_u32("qwen35.attention.head_count", m["n_heads"]),
        _kv_u32("qwen35.attention.head_count_kv", m["n_kv_heads"]),
        _kv_u32("qwen35.attention.key_length", m["head_dim"]),
        _kv_u32("qwen35.attention.value_length", m["head_dim"]),
        _kv_u32("qwen35.embedding_length", m["hidden"]),
        _kv_u32("qwen35.feed_forward_length", m["ffn"]),
        _kv_f32("qwen35.rope.freq_base", m["theta"]),
        _kv_f32("qwen35.attention.layer_norm_rms_epsilon", m["eps"]),
        _kv_u32("qwen35.rope.dimension_count", int(m["head_dim"] * m["prf"])),
        _kv_u32("qwen35.full_attention_interval", m["interval"]),
        _kv_u32("qwen35.ssm.group_count", nk),
        _kv_u32("qwen35.ssm.state_size", dk),
        _kv_u32("qwen35.ssm.time_step_rank", nv),
        _kv_u32("qwen35.ssm.inner_size", value_dim),
        _kv_u32("qwen35.ssm.conv_kernel", m["conv_k"]),
        # The loader takes cfg.vocab from this list's length; the strings
        # themselves are never used by the forward.
        _kv_arr_str("tokenizer.ggml.tokens",
                    ["t%d" % t for t in range(m["vocab"])]),
    ]

    offsets, off = [], 0
    for _, arr, _dims in tensors:
        offsets.append(off)
        off = ((off + arr.nbytes + ALIGNMENT - 1) // ALIGNMENT) * ALIGNMENT

    infos = [_tensor_info(n, TT_F32, d, o)
             for (n, _a, d), o in zip(tensors, offsets)]

    header = GGUF_MAGIC + struct.pack("<I", GGUF_VERSION)
    header += struct.pack("<Q", len(tensors))
    header += struct.pack("<Q", len(kvs))
    body = header + b"".join(kvs) + b"".join(infos)
    body += b"\x00" * ((-len(body)) % ALIGNMENT)

    data = bytearray()
    for (_n, arr, _d), o in zip(tensors, offsets):
        data += b"\x00" * (o - len(data))
        data += arr.astype("<f4").tobytes()

    path = pathlib.Path(path)
    path.write_bytes(body + bytes(data))
    print(f"wrote {path} ({len(tensors)} F32 tensors, tiled value-head order "
          f"{hf_of})")


if __name__ == "__main__":
    if "--tok" in sys.argv:
        write_tok_fixture("/Users/macmini/models/qwen36-27b-8bit",
                          "tests/fixtures/tok_cases.jsonl")
    elif "--st" in sys.argv:
        write_mini_safetensors("tests/fixtures/mini_st")
        write_mini_model_st("tests/fixtures/mini_model_st")
        write_mini_model_st("tests/fixtures/mini_model_st_partial", drop="linear_attn.dt_bias")
    elif "--ops" in sys.argv:
        write_op_fixtures("tests/fixtures/ops.bin")
    elif "--hybrid" in sys.argv:
        write_hybrid_op_fixtures("tests/fixtures/hybrid_ops.bin")
    elif "--fwd" in sys.argv:
        write_mini_fwd("tests/fixtures/mini_fwd")
    else:
        write_mini_gguf("tests/fixtures/mini.gguf")
        print("wrote tests/fixtures/mini.gguf")
