#!/usr/bin/env python3
"""Generate synthetic GGUF v3 fixtures for surge's test suite.

Stdlib only (struct). Run once at authoring time; the produced binary is
committed to tests/fixtures/ and is not regenerated by the build.
"""
import json
import pathlib
import struct
import sys

GGUF_MAGIC = b"GGUF"
GGUF_VERSION = 3
ALIGNMENT = 32

# sg_gguf_kv_type values, must match the enum in surge.h.
T_I32 = 5
T_F32 = 6
T_BOOL = 7
T_U32 = 4
T_STR = 8
T_ARR = 9

# sg_tensor_type values, must match the enum in surge.h.
T_F32 = 0
T_Q8_0 = 8


def _str(s: str) -> bytes:
    b = s.encode("utf-8")
    return struct.pack("<Q", len(b)) + b


def _kv_str(key: str, value: str) -> bytes:
    return _str(key) + struct.pack("<I", T_STR) + _str(value)


def _kv_u32(key: str, value: int) -> bytes:
    return _str(key) + struct.pack("<I", T_U32) + struct.pack("<I", value)


def _kv_i32(key: str, value: int) -> bytes:
    return _str(key) + struct.pack("<I", T_I32) + struct.pack("<i", value)


def _kv_bool(key: str, value: bool) -> bytes:
    return _str(key) + struct.pack("<I", T_BOOL) + struct.pack("<B", 1 if value else 0)


def _kv_arr_u32(key: str, values: list) -> bytes:
    out = _str(key) + struct.pack("<I", T_ARR) + struct.pack("<I", T_U32)
    out += struct.pack("<Q", len(values))
    for v in values:
        out += struct.pack("<I", v)
    return out


def _tensor_info(name: str, ttype: int, dims: list, offset: int) -> bytes:
    out = _str(name)
    out += struct.pack("<I", len(dims))
    for d in dims:
        out += struct.pack("<Q", d)
    out += struct.pack("<I", ttype)
    out += struct.pack("<Q", offset)
    return out


def write_mini_gguf(path: str) -> None:
    """Write the small GGUF v3 fixture used by tests/test_gguf.c.

    Metadata: general.architecture="qwen3_5" (str),
    qwen3_5.block_count=2 (u32), test.arr=[1,2,3] (u32 array),
    test.i32=-42 (i32), test.bool=true (bool).
    Tensors: t.f32 f32[4] = [1.0, 2.0, 3.0, 4.0];
    t.q8 Q8_0[32], one block: f16 scale 0.5 + int8 0..31.
    """
    kvs = [
        _kv_str("general.architecture", "qwen3_5"),
        _kv_u32("qwen3_5.block_count", 2),
        _kv_arr_u32("test.arr", [1, 2, 3]),
        _kv_i32("test.i32", -42),
        _kv_bool("test.bool", True),
    ]

    f32_nbytes = 4 * 4  # t.f32: f32[4]
    q8_nbytes = 34  # t.q8: Q8_0[32] = 1 block (2-byte f16 scale + 32 int8)

    off_f32 = 0
    off_q8 = ((off_f32 + f32_nbytes + ALIGNMENT - 1) // ALIGNMENT) * ALIGNMENT

    tensors = [
        _tensor_info("t.f32", T_F32, [4], off_f32),
        _tensor_info("t.q8", T_Q8_0, [32], off_q8),
    ]

    header = GGUF_MAGIC + struct.pack("<I", GGUF_VERSION)
    header += struct.pack("<Q", len(tensors))
    header += struct.pack("<Q", len(kvs))

    body = header + b"".join(kvs) + b"".join(tensors)
    pad = (-len(body)) % ALIGNMENT
    body += b"\x00" * pad
    assert len(body) % ALIGNMENT == 0

    data = bytearray()
    data += struct.pack("<4f", 1.0, 2.0, 3.0, 4.0)  # t.f32
    data += b"\x00" * (off_q8 - len(data))  # pad up to t.q8's offset
    data += struct.pack("<H", 0x3800)  # f16(0.5) scale
    data += struct.pack("<32b", *range(32))  # int8 0..31
    assert len(data) == off_q8 + q8_nbytes

    out = pathlib.Path(path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_bytes(body + bytes(data))


# 24 cases for tests/test_tok.c, covering: empty string, ascii prose, digits,
# contractions, code with braces/tabs, leading/trailing/internal/mixed
# whitespace, bare newlines, blank lines, CRLF, accented Latin, CJK, Hangul,
# emoji, mixed emoji+CJK+ascii, punctuation runs, and a long no-space token
# (URL). None contain literal special-token strings (e.g. "<|...|>"), since
# sg_tok_encode is plain byte-level BPE with no added-token recognition.
TOK_FIXTURE_CASES = [
    "",
    "Hello, world!",
    "The quick brown fox jumps over 13 lazy dogs, 42 times.",
    "I can't believe it's not butter. We'll see; they've done it already.",
    "0123456789",
    "Total: 5 items, cost $9.99 (approx).",
    "def foo(x):\n\treturn {'a': 1, 'b': [1, 2, 3]}\n",
    "if (x > 0) {\n    return x;\n} else {\n    return -x;\n}",
    "   leading spaces",
    "trailing spaces   ",
    "a    b     c",
    "\n\n\n",
    "line1\nline2\n\nline3",
    "a\tb\tc",
    "line1\r\nline2\r\n",
    "café naïve résumé Zürich",
    "日本語のテスト。これはテストです。",
    "안녕하세요 세계",
    "emoji test 😀🚀🎉",
    "Hello 世界 🌍!",
    "Wait... what?! No way!!! (really?)",
    "https://example.com/path?query=1&other=2",
    "line1\nline2\ttabbed",
    "   \t  mixed   whitespace\t\t  runs  ",
]


def write_tok_fixture(tokenizer_dir: str, out_path: str) -> None:
    """Generate tests/fixtures/tok_cases.jsonl from the real HF tokenizer.

    Each line is {"text": ..., "ids": [...]}, ids from
    AutoTokenizer.encode(text, add_special_tokens=False) (no BOS/EOS; Qwen's
    add_bos_token is false and there is no TemplateProcessing post_processor
    on this tokenizer, so this matches plain encode/decode with no implicit
    special tokens). Written with ensure_ascii=False so non-ASCII text is
    stored as raw UTF-8 bytes, not \\uXXXX escapes (surrogate pairs for
    astral-plane emoji would otherwise need extra decoding on the C side).

    Requires the dsv4-venv interpreter (has transformers installed):
        /Users/macmini/models/dsv4-venv/bin/python tools/make_fixtures.py --tok
    """
    from transformers import AutoTokenizer

    tok = AutoTokenizer.from_pretrained(tokenizer_dir)

    assert len(TOK_FIXTURE_CASES) == 24, \
        f"expected 24 fixture cases, got {len(TOK_FIXTURE_CASES)}"

    out = pathlib.Path(out_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("w", encoding="utf-8") as f:
        for text in TOK_FIXTURE_CASES:
            ids = tok.encode(text, add_special_tokens=False)
            decoded = tok.decode(ids)
            assert decoded == text, f"roundtrip mismatch for {text!r}: {decoded!r}"
            line = json.dumps({"text": text, "ids": ids}, ensure_ascii=False)
            f.write(line + "\n")

    print(f"wrote {out_path} ({len(TOK_FIXTURE_CASES)} cases)")


def _f32_to_bf16_bytes(x: float) -> bytes:
    """Round-to-nearest-even float32 -> bf16, packed as a little-endian u16.

    All six fixture values below (0.5, 1, 2, 3, 4, 5) are exactly
    representable in bf16 (zero mantissa bits below the truncation point),
    so this is a plain truncation for them; the round-to-nearest-even bias
    is included anyway so the helper is correct for arbitrary floats.
    """
    bits = struct.unpack("<I", struct.pack("<f", x))[0]
    rounding_bias = 0x7FFF + ((bits >> 16) & 1)
    bits = (bits + rounding_bias) >> 16
    return struct.pack("<H", bits & 0xFFFF)


def write_mini_safetensors(out_dir: str) -> None:
    """Write the small safetensors fixture used by tests/test_st.c.

    Single-shard model dir (no model.safetensors.index.json) containing
    model.safetensors: one bf16 tensor "w" shape [2, 3], row-major values
    0.5, 1, 2, 3, 4, 5; plus config.json {"hidden_size": 3}.
    """
    values = [0.5, 1.0, 2.0, 3.0, 4.0, 5.0]
    data = b"".join(_f32_to_bf16_bytes(v) for v in values)
    assert len(data) == 12

    header_obj = {
        "w": {"dtype": "BF16", "shape": [2, 3], "data_offsets": [0, len(data)]},
    }
    header_json = json.dumps(header_obj).encode("utf-8")
    # Pad the header with spaces (valid insignificant JSON whitespace) so the
    # data section starts 8-byte aligned, per the safetensors convention.
    total_prefix = 8 + len(header_json)
    pad = (-total_prefix) % 8
    header_json += b" " * pad

    out = pathlib.Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)

    with (out / "model.safetensors").open("wb") as f:
        f.write(struct.pack("<Q", len(header_json)))
        f.write(header_json)
        f.write(data)

    (out / "config.json").write_text(json.dumps({"hidden_size": 3}), encoding="utf-8")
    print(f"wrote {out_dir}/model.safetensors and {out_dir}/config.json")


if __name__ == "__main__":
    if "--tok" in sys.argv:
        write_tok_fixture("/Users/macmini/models/qwen36-27b-8bit",
                          "tests/fixtures/tok_cases.jsonl")
    elif "--st" in sys.argv:
        write_mini_safetensors("tests/fixtures/mini_st")
    else:
        write_mini_gguf("tests/fixtures/mini.gguf")
        print("wrote tests/fixtures/mini.gguf")
