#!/usr/bin/env python3
"""Generate synthetic GGUF v3 fixtures for surge's test suite.

Stdlib only (struct). Run once at authoring time; the produced binary is
committed to tests/fixtures/ and is not regenerated by the build.
"""
import pathlib
import struct

GGUF_MAGIC = b"GGUF"
GGUF_VERSION = 3
ALIGNMENT = 32

# sg_gguf_kv_type values, must match the enum in surge.h.
T_U32 = 4
T_STR = 8
T_ARR = 9

# sg_tensor_type values, must match the enum in surge.h.
T_F32 = 0
T_Q8_0 = 8


def _str(s: str) -> bytes:
    b = s.encode("utf-8")
    return struct.pack("<Q", len(b)) + b


def _kv_str(key: str, value: str) -> bytes:
    return _str(key) + struct.pack("<I", T_STR) + _str(value)


def _kv_u32(key: str, value: int) -> bytes:
    return _str(key) + struct.pack("<I", T_U32) + struct.pack("<I", value)


def _kv_arr_u32(key: str, values: list) -> bytes:
    out = _str(key) + struct.pack("<I", T_ARR) + struct.pack("<I", T_U32)
    out += struct.pack("<Q", len(values))
    for v in values:
        out += struct.pack("<I", v)
    return out


def _tensor_info(name: str, ttype: int, dims: list, offset: int) -> bytes:
    out = _str(name)
    out += struct.pack("<I", len(dims))
    for d in dims:
        out += struct.pack("<Q", d)
    out += struct.pack("<I", ttype)
    out += struct.pack("<Q", offset)
    return out


def write_mini_gguf(path: str) -> None:
    """Write the small GGUF v3 fixture used by tests/test_gguf.c.

    Metadata: general.architecture="qwen3_5" (str),
    qwen3_5.block_count=2 (u32), test.arr=[1,2,3] (u32 array).
    Tensors: t.f32 f32[4] = [1.0, 2.0, 3.0, 4.0];
    t.q8 Q8_0[32], one block: f16 scale 0.5 + int8 0..31.
    """
    kvs = [
        _kv_str("general.architecture", "qwen3_5"),
        _kv_u32("qwen3_5.block_count", 2),
        _kv_arr_u32("test.arr", [1, 2, 3]),
    ]

    f32_nbytes = 4 * 4  # t.f32: f32[4]
    q8_nbytes = 34  # t.q8: Q8_0[32] = 1 block (2-byte f16 scale + 32 int8)

    off_f32 = 0
    off_q8 = ((off_f32 + f32_nbytes + ALIGNMENT - 1) // ALIGNMENT) * ALIGNMENT

    tensors = [
        _tensor_info("t.f32", T_F32, [4], off_f32),
        _tensor_info("t.q8", T_Q8_0, [32], off_q8),
    ]

    header = GGUF_MAGIC + struct.pack("<I", GGUF_VERSION)
    header += struct.pack("<Q", len(tensors))
    header += struct.pack("<Q", len(kvs))

    body = header + b"".join(kvs) + b"".join(tensors)
    pad = (-len(body)) % ALIGNMENT
    body += b"\x00" * pad
    assert len(body) % ALIGNMENT == 0

    data = bytearray()
    data += struct.pack("<4f", 1.0, 2.0, 3.0, 4.0)  # t.f32
    data += b"\x00" * (off_q8 - len(data))  # pad up to t.q8's offset
    data += struct.pack("<H", 0x3800)  # f16(0.5) scale
    data += struct.pack("<32b", *range(32))  # int8 0..31
    assert len(data) == off_q8 + q8_nbytes

    out = pathlib.Path(path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_bytes(body + bytes(data))


if __name__ == "__main__":
    write_mini_gguf("tests/fixtures/mini.gguf")
    print("wrote tests/fixtures/mini.gguf")
